name: Publish PHPUnit Coverage Results
on:
  push:
    branches:
      - main
jobs:
  phpunit:
    name: Run and Deploy Coverage Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' # Adjust the PHP version as needed
          extensions: mbstring, dom, xml, bcmath
          ini-values: memory_limit=-1
          coverage: xdebug
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --coverage-html=coverage
      # Rename Underscore Directories
      - name: Rename Directories
        run: |
          mv coverage/_css coverage/css
          mv coverage/_js coverage/js
          mv coverage/_icons coverage/icons
      - name: Fix Links in HTML Files
        run: bash ./fix_coverage.sh
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          destination_dir: coverage # Publish into the 'coverage/' subdirectory
          keep_files: true # Preserve existing content like README.md